# 基础版本信息配置
SERVER:
  NAME: open2lisapi
  VERSION: v1.0.1
  DEBUG: True
  SECRET_KEY: IbelivemeIcanfly
  ADMIN: admin
  ADMIN_AUTH_LIST: ['test1234']


# 日志
LOG:
  LOG_DIR: log
  LOG_LEVEL: debug
  LOG_FORMATTER: '%(asctime)s - %(pathname)s[line:%(lineno)d] - %(levelname)s - %(message)s'
  LOG_FILENAME_PREFIX: open2lisapi


# 数据库
DB:
  DB_LINK: mysql+pymysql://twtoolbox:2dcc0521bd32dc5100c6d65a1effa8e6@121.4.56.169:3306/twtoolbox?charset=utf8


# email
MAIL:
  MAIL_SERVER: smtp.163.com
  MAIL_PORT: 25
  MAIL_USE_SSL: True
  MAIL_USERNAME: XXXXXX@163.com
  MAIL_PASSWORD: XXXXXX


# 用户配置
USER:
  AVATAR: http://store.pygo2.top/w.jpg
  PASSWORD: abc1234
  TIMELINE: 10
  INTRODUCTION: 这家伙很懒，什么也没留下......
  STORE_BASE_URL: http://avatar.pygo2.top
  STORE_NAME: avatar-default


# 云对象存储
STORE:
  # 缓存路径【绝对路径】
  # WIN：E:\_CACHE     MacOS：/Users/gaomingliang/Downloads/_CACHE
  CACHE: /Users/gaomingliang/Downloads/_CACHE
  BASE_URL: http://store.pygo2.top
  ACCESS: mRF0cKGUJcfv7ry_Wyvc24cDNWEQz9DAKo_UOn0G
  SECRET: xabmlB9zZ_MRwtgofQJzUxINnmcO_VUfkXYILx_Q
  SPACE_NAME: twtoolbox


# 菜单
MENU:
  MENU_ROOT_ID: 0
  MENU_ONE_LEVEL: 1


# 图片
IMAGE:
  QUALITY: 100
  WIDTH: 700


# 文章
ARTICLE:
  LIMIT: 10


# 文档基础配置
OFFICE:
  STORE_BK: True
  LIMIT: 15
  SHEET_NUM_LIMIT: 12
  SHEET_NAME_LIMIT: 65


# PDF2WORD
CONVERT:
  MULPRO: True


# 权限基础配置
AUTH:
  LIMIT: 15
  NUM: 45


# dingTalk配置
DINGTALK:
  BASE_URL: https://oapi.dingtalk.com/
  TOKEN_URL: gettoken
  TITLE: True
  ADD_IMAGE:
  CONTROL: []
  INTERVAL: 0.5


# 企业微信配置
QYWX:
  BASE_URL: https://qyapi.weixin.qq.com
  ACCESS_TOKEN: /cgi-bin/gettoken
  SEND_MESSAGE: /cgi-bin/message/send
  SEND_BACK: /cgi-bin/message/recall


# 其他配置
OTHERS:
  NOBN: NoNameBody